name: API Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        working-directory: ./
        run: docker build . -t bugg86/botvex:latest

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push the image to Docker Hub
        run: docker push bugg86/botvex

      - name: Pull the image to VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script:
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/botvex:latest
            docker stop botvex || true
            docker rm botvex || true
            docker run -d -p 80:80 --name botvex ${{ secrets.DOCKERHUB_USERNAME }}/botvex:latest